//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace senproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EERTEntities2 : DbContext
    {
        public EERTEntities2()
            : base("name=EERTEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerChat> CustomerChats { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
